### ISSUE TITLE
Question: Usage of void 0?

### ISSUE THREAD

**Issue by btnwtn** [bevacqua/sixflix#2]
Hey I was just looking through the source and noticed this line:
```
if (result === void 0) {
```
https://github.com/bevacqua/sixflix/blob/master/index.js#L6

I've never come across this sort of expression before. Why did you choose this over something like the examples below?

```
if (result === undefined) {
```

or

```
if (!result) {
```

**Comment by stuartpb** [comment]
It's a way of getting the `undefined` value reliably, without depending on `window.undefined`. (It's also shorter.) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void

`if (!result)` wouldn't skip the test after it has run and evaluated to `false`.

**Comment by bevacqua** [comment]
What @stuartpb said!

**Comment by btnwtn** [comment]
@stuartpb can you clarify on what "without depending on `window.undefined`" this means? Does this mean that this code can execute in a Node environment? That's the only case that `window.undefined` would be... undefined right?

**Comment by bevacqua** [comment]
It means that outside of strict mode someone could do `undefined = "lol, javascript"` and you'd pick up this value, while `void 0` guarantees you pick up `undefined`.

**Comment by btnwtn** [comment]
ahhhh I see. thanks!
