### ISSUE TITLE
Modular builds?

### ISSUE THREAD

**Issue by stuartpb** [bevacqua/sixflix#3]
Per [the gist](https://gist.github.com/DaBs/89ccc2ffd1d435efdacff05248514f38#gistcomment-1976435), this tests for:

- [x] Classes
- [x] Enhanced object literals
- [x] Template strings
- [x] Destructuring
- [x] Default + Rest + Spread
- [x] `let` + `const`
- [x] Iterators + `for..of`
- [x] Generators (`function* ()`)
- [x] Unicode (ಠ_ಠ)
- [x] Proxies
- [x] Symbols
- [x] Subclassable built-ins
- [x] Promises
- [x] Arrows
- [x] New additions to APIs:
`Math`
`Number`
`String`
`Array`
`Object`

However, not all of us *need* support for all these features for our ES6 code to run. Would it be possible to build some sort of modular version of the test string that omits tests / replaces with shorter ES5 setup stubs, for testing subsets of these features?

**Comment by bevacqua** [comment]
This package is super small already. I would rather spend my treeshaking efforts elsewhere.

**Comment by bevacqua** [comment]
That said, if you feel strongly about this, I invite you to submit a PR with a CLI that generates different `sixflix` builds based on which features you want to test for.

So `$ sixflix` would default to all features, while `$ sixflix --arrows --classes` would only feature-test those two. I'd do it by printing the module to stdout.
